### ISSUE TITLE
Entity:AddCharmed(int duration) does not appear to exist

### ISSUE THREAD

**Issue by Somdudewillson** [wofsauge/IsaacDocs#121]
Can be seen via `lua Isaac.Spawn(EntityType.ENTITY_PORTAL,1,0,Isaac.GetPlayer(0).Position,Vector.Zero,player):AddCharmed(1);` in the console.

**Comment by wofsauge** [comment]
Thanks for the report. Ive removed the mention of that function and updated the description for it
