### ISSUE TITLE
Page for ItemPool class should say HOW to get the ItemPool class

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#133]
This also applies to the other various classes in the API that only have one way to get them.

**Comment by wofsauge** [comment]
Added it for ItemPool and some other classes now, but this is a really tedious task to do so it will take a while.

here is the progress so far:
(Green = done, Red: Wont do, mostly because they have constructors)
![image](https://user-images.githubusercontent.com/245725/127233974-e2eb18c8-232d-4adc-9da6-9777bb30166f.png)

**Comment by Zamiell** [comment]
this issue was mostly about the classes that only have 1 way to get them (like e.g. the HUD class).
i dont think we need to document all the ways to get every class.

**Comment by Zamiell** [comment]
also, for the global classes, we should make a note that they are global and that you don't have to "get" them.

for example, at the top of the Isaac class, something like the folowing:

"The Isaac class is provided as a global variable, so you can use it in any code without calling a constructor."

**Comment by Zamiell** [comment]
should i make a separate issue for that?

**Comment by wofsauge** [comment]
> should i make a separate issue for that?

Definetly! This issue here is already big enough of a scope.

**Comment by Zamiell** [comment]
by the way, if you want to get a programmatic list of what classes get other classes, you can open up [isaac-typescript-definitions](https://github.com/IsaacScript/isaac-typescript-definitions) in vscode and press alt+shift+f12

**Comment by Zamiell** [comment]
(i dont know if you've been doing this manually or whatever)

**Comment by wofsauge** [comment]
Finally done with commit df6f832f8b30a701e2da7a1d25ba254d8d26b0fa
