### ISSUE TITLE
Update description for Level:SetNextStage

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#134]
1) Provide a description of what it ACTUALLY does.
2) In the current description, it says "use other functions". WHAT other functions? Provide a code snippet for a full level transition from start to finish.

**Comment by im-tem** [comment]
i am too lazy to write a code snippet but description was updated
https://github.com/wofsauge/IsaacDocs/commit/dbeb32c57f5bd49cb68fb134d62432219a6060c6
