### ISSUE TITLE
Isaac.GetPlayerTypeByName should specify the return value if not found

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#138]
which is -1

**Comment by wofsauge** [comment]
Added those infos to all Isaac.GetByName functions now.

**Comment by Zamiell** [comment]
note: i only specifically tested GetPlayerTypeByName for -1
did you test the other ones?

**Comment by wofsauge** [comment]
> note: i only specifically tested GetPlayerTypeByName for -1
> did you test the other ones?

yes i tested all of them. the only one that wasnt -1 was GetEntityTypeByName, which returns 0

**Comment by Zamiell** [comment]
interesting.
i wonder why that is lol
