### ISSUE TITLE
Change argument of EntityPlayer.AddCollectible

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#147]
Change addConsumables to firstTimePickingUp, and document that setting it to false will:
1) not grant any consumables (e.g. Remote Detonator)
2) not count towards transformations

**Comment by wofsauge** [comment]
Added this information now

**Comment by Zamiell** [comment]
please change AddTrinket as well so that it is consistent

**Comment by wofsauge** [comment]
done
