### ISSUE TITLE
document GetGridPath / SetGridPath

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#157]
Grid path is a property of a square that represents a pathfinding "cost".
Some enemies set it to 900 when they path over a square.
Fireplaces set it to 950.
Most grid entities set it to 1000 or higher (so that enemies will not try to path through the grid entity.)

If a grid square has a path higher than 0, it can prevent a grid entities from being spawned on that square. Thus, you can get around it by resetting the grid path to 0, and then spawning the grid entity.

**Comment by wofsauge** [comment]
Added in f7c362c821c07c0c40887a748254bdc03f5c5244
