### ISSUE TITLE
GetCurrentRoomDesc should not be used

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#174]
it returns a read only copy of RoomDescriptor.
however, if you try to modify any of the values, instead of throwing an error, it will just explicitly fail.
1) the docs should document this behavior.
2) I think the docs should advise users to simply NEVER use this method and instead always use `GetRoomByIdx(currentRoomIndex)`.

**Comment by wofsauge** [comment]
Added these informations in 479f345d64d7f8f00b67f7f4407bd52a6d0f8509
