### ISSUE TITLE
Document Bug with Pickup.Price

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#179]
On Tainted Keeper, items are supposed to have a price. But any items spawned with Lua free, so you have to manually set a price. On the next frame after assigning a price (e.g. 1), it will snap to the correct price (e.g. 15) because of the AutoUpdatePrice feature.

This method works most of the time. However, it breaks in special rooms (e.g. Angel Rooms) such that sometimes, the price will snap to wrong values, such as 24, 99, and so on. The fix for this is to set ShopItemId to an arbitrary negative value (e.g. -1).

**Comment by wofsauge** [comment]
added already with commit 1dba4c0
