### ISSUE TITLE
Document room:Update()

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#180]
In the docs, it says that `room:Update()` is useless, but it isn't useless.

- Take the case of spawning a trapdoor where a pit already exists.
- If you simply remove the pit and try to spawn a trapdoor, the pit will be successfully removed, but the trapdoor will not appear.
- The solution is to remove the pit, call `room:Update()`, and then spawn the trapdoor.

Thus, I think that the docs should recommend that it is best practice to always call `room:Update()` after removing any grid entity. This recommendation should appear on both the section for `room:Update()` and `room:RemoveGridEntity()`.

Separately, please link to [this issue](https://github.com/Meowlala/RepentanceAPIIssueTracker/issues/211) in the documentation for `room:Update()`.

**Comment by wofsauge** [comment]
Updated infos in 7dc6909f1a6c23ba51ae77945c2e2911268c66df
