### ISSUE TITLE
Document GridEntity.Desc

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#181]
Both the `Desc` property and the `GetSaveState()` method of the `GridEntity` class return a `GridEntityDesc` object, which is confusing.

I spoke with Kil today and he confirmed that yes, they return the exact same thing, and it is preferable for modders to use the method rather than the property.

Thus, I will configure IsaacScript to throw a compiler error whenever `Desc` is accessed, and the docs should be updated to advise people to not use it.

**Comment by DolosKurosu** [comment]
Nice. Good to have that clarified.

**Comment by wofsauge** [comment]
Added this info with commit 825850a0a5779a24249f642d717a4946a7fadbdc
