### ISSUE TITLE
Document InitializeDevilAngelRoom

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#183]
- By calling this function, it "locks in" the choice between a Devil Room and an Angel Room for the current floor.
- Once the room is initialized, the appropriate door will spawn after killing the boss.
- This function still works to grant a Devil Room even if the player has the Eucharist.
- Calling this function twice will have no effect, because the room will already have been initialized. For example, this means that if you force an Angel Room, you can't change it back to a Devil Room later on.
  - However, you can get around this restriction by calling `level:GetRoomByIdx(GridRooms.ROOM_DEVIL_IDX).Data = nil`, which will uninitialize the room.
- The function must be called before the Devil Room or Angel Room door appears in a boss room, because at that point, the particular room will already have been initialized by the game.
  - Again, you can get around this restriction with the same method as the previous bullet point.

**Comment by wofsauge** [comment]
Added infos with commit 533413dc252ba05ec40a0d374eb8f87f47425d5a
