### ISSUE TITLE
Document Level.GetRoomByIdx

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#185]
It should be noted that:

- You can provide any arbitrary number as an argument and get back a valid `RoomDescriptor` object, so error checking is recommended.
- The `GridIndex` property of an invalid `RoomDescriptor` object seems to always be -1. Note that this is not actually the `RoomDescriptor` of the Devil Room, as it will have a different `VisitedCount`.

**Comment by wofsauge** [comment]
Added infos in db0329f873a0ff8f34bcb900e920de22e423f8c0
