### ISSUE TITLE
Tutorials --> Example Project is out of date

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#187]
It says 
`C:\Users\[YOURUSERNAME]\Documents\My Games\Binding of Isaac Afterbirth+ Mods`
but this is no longer correct in Rep.
Might as well delete the AB+ instructions since very few if any will ever mod that anymore.

**Comment by wofsauge** [comment]
Do you know the path for Linux mods in Repentance?

**Comment by Zamiell** [comment]
its complicated because linux uses proton, so it emulates windows.
honestly i wouldn't worry about including this information, fuck linux users :)

**Comment by wofsauge** [comment]
Changed the path in commit d8f5f23157d7ee62b133b87a8176d012feac7fab
