### ISSUE TITLE
SecondaryActiveItem doesn't work anymore in Rep

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#188]
and you might as well remove ActiveItemDesc as well, since it isn't used for anything

**Comment by wofsauge** [comment]
added warning message in a58aa69bdd806cf0f433a31e1979e477201008cb

i will leave the class in, since we will need it when the next patch drops. i therefore will also leave the function in, since its a nice place to inform people of the inaccessability, but the potential of the class.
