### ISSUE TITLE
Document EntityPlayer.GetActiveSubCharge

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#190]
I don't know exactly what it does, but it should be documented that:

- It is nit related to the Battery. This function always returns 0, regardless of what the Battery charge it. You get the Battery charge by using `EntityPlayer.GetBatteryCharge`.
- It is not related to 4.5 Volt. When the player has 4.5 volt, the `EntityPlayer.GetCharge` method works as expected. There is not a way to get the "partial" charge towards the next tick of charge. This function always returns 0, regardless of what the partial charge is.
- It is not related to the Schoolbag. This function always returns 0, regardless of the charge of the Schoolbag item. You can get the Schoolbag item charge by using the `EntityPlayer.GetCharge` method with the correct `ActiveSlot` argument.

**Comment by wofsauge** [comment]
Added info in 7cd3bb00955e1fcd7fb697d29b6838f57ea28f39
