### ISSUE TITLE
MultiShot documentation is wrong

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#193]
1.

In the `EntityPlayer.GetMultiShotParams` method, it says:
"Since it returns UserData, this function is unusable and therefore broken."

However, this is wrong because it can be used in the `EntityPlayer.GetMultiShotPositionVelocity` method.

2.

In the `EntityPlayer.GetMultiShotPositionVelocity` method, it says:
"Call this function in a loop with values from 0 to MultiShotParams.NumProjectiles-1 (inclusive)"

However, this is wrong because `MultiShotParams` does not have a `NumProjectiles` property.

**Comment by wofsauge** [comment]
Added infos with commit 927c55d3ef061f4f9c8e2cb3f03daf755f8607ee
