### ISSUE TITLE
Additional return behaviour for callbacks

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/IsaacDocs#22]
@Wofsauge some notes for the documentation
MC_NPC_UPDATE
MC_POST_UPDATE
MC_POST_RENDER
MC_USE_ITEM
MC_POST_PEFFECT_UPDATE
MC_USE_CARD
MC_FAMILIAR_UPDATE 
MC_FAMILIAR_INIT 
MC_EVALUATE_CACHE 
MC_POST_PLAYER_INIT 
MC_USE_PILL 
MC_POST_CURSE_EVAL 
MC_INPUT_ACTION
MC_POST_GAME_STARTED 
MC_POST_GAME_END 
MC_PRE_GAME_EXIT 
MC_POST_NEW_LEVEL 
MC_POST_NEW_ROOM 
MC_GET_CARD 
MC_EXECUTE_CMD
MC_PRE_ENTITY_SPAWN 
MC_POST_FAMILIAR_RENDER 
MC_POST_NPC_INIT 
MC_POST_NPC_RENDER 
MC_POST_NPC_DEATH 
MC_POST_PLAYER_UPDATE 
MC_POST_PLAYER_RENDER 
MC_POST_PICKUP_INIT 
MC_POST_PICKUP_UPDATE 
MC_POST_PICKUP_RENDER 
MC_POST_PICKUP_SELECTION 
MC_POST_TEAR_INIT 
MC_POST_TEAR_UPDATE 
MC_POST_TEAR_RENDER 
MC_POST_PROJECTILE_INIT 
MC_POST_PROJECTILE_UPDATE 
MC_POST_PROJECTILE_RENDER 
MC_POST_LASER_INIT 
MC_POST_LASER_UPDATE 
MC_POST_LASER_RENDER 
MC_POST_KNIFE_INIT 
MC_POST_KNIFE_UPDATE 
MC_POST_KNIFE_RENDER 
MC_POST_EFFECT_INIT 
MC_POST_EFFECT_UPDATE 
MC_POST_EFFECT_RENDER 
MC_POST_BOMB_INIT 
MC_POST_BOMB_UPDATE 
MC_POST_BOMB_RENDER 
MC_POST_FIRE_TEAR 
MC_PRE_GET_COLLECTIBLE 
MC_POST_GET_COLLECTIBLE
MC_GET_PILL_COLOR 
MC_GET_PILL_EFFECT 
MC_GET_TRINKET
MC_POST_ENTITY_REMOVE 
MC_POST_ENTITY_KILL 
MC_PRE_ROOM_ENTITY_SPAWN
later callbacks continue regardless of return value

MC_ENTITY_TAKE_DMG 
MC_PRE_USE_ITEM 
returning any value besides nil prevents later callbacks from being called

MC_PRE_FAMILIAR_COLLISION 
MC_PRE_NPC_COLLISION 
MC_PRE_PLAYER_COLLISION 
MC_PRE_PICKUP_COLLISION 
MC_PRE_TEAR_COLLISION 
MC_PRE_PROJECTILE_COLLISION 
MC_PRE_KNIFE_COLLISION 
MC_PRE_BOMB_COLLISION 
MC_PRE_NPC_UPDATE 
MC_PRE_SPAWN_CLEAN_AWARD 
later callbacks never get called regardless of return value

other notes:

MC_POST_CURSE_EVAL
MC_GET_CARD 
MC_POST_PICKUP_SELECTION
MC_PRE_GET_COLLECTIBLE 
MC_POST_GET_COLLECTIBLE
MC_GET_PILL_COLOR 
MC_GET_PILL_EFFECT 
MC_GET_TRINKET
the last callback to return a valid return value wins out and overwrites previous callbacks' return values

MC_POST_CURSE_EVAL
MC_GET_CARD 
MC_PRE_GET_COLLECTIBLE 
MC_POST_GET_COLLECTIBLE
MC_GET_PILL_COLOR 
MC_GET_PILL_EFFECT 
MC_GET_TRINKET
returning something that isnt a number or nil crashes the game when called

MC_PRE_ENTITY_SPAWN 
crashes when returning a table with incomplete values

MC_LEVEL_GENERATOR 
gay

MC_GET_SHADER_PARAMS 
idk how to test

MC_EXECUTE_CMD
returning a string prints it to the console

**Comment by piber20** [comment]
about the "the last callback to return a valid return value wins out and overwrites previous callbacks' return values" note

MC_POST_CURSE_EVAL
if a callback returns a number it will be the Curses arg in later callbacks

MC_GET_CARD
no change to Card arg

MC_POST_PICKUP_SELECTION
if a callback returns a table containing the variant and subtype to replace it will be applied to the variant and subtype args in later callbacks

MC_PRE_GET_COLLECTIBLE 
no changes

MC_POST_GET_COLLECTIBLE
no change to SelectedCollectible arg

MC_GET_PILL_COLOR 
no changes

MC_GET_PILL_EFFECT 
no change to SelectedPillEffect arg

MC_GET_TRINKET
no change to SelectedTrinket arg
