### ISSUE TITLE
Removed CollectibleType enums may be reused in new updates

### ISSUE THREAD

**Issue by V-Copy** [wofsauge/IsaacDocs#236]
While working on a mod, I found out that the CollectibleType 59 happens to be the Birthright version of the Book of Belial that Judas gets if he picks up Birthright without having obtained a different active item. Other CollectibleTypes that were removed may be used behind the scenes in a similar manner.

You can verify this by starting a game as Judas, using the command
lua print(string.format("%01d", Isaac.GetPlayer(0):GetActiveItem(0)))
which would return 34 (the normal Book of Belial), giving yourself Birthright, and repeating the command, which for me returns 59.

**Comment by Zamiell** [comment]
what action do you suggest? we can't add arbitrary enums to that page because they won't exist in end-user enum.lua files

**Comment by V-Copy** [comment]
I'm not exactly sure what that means or what the problem actually is (my apologies, I'm very new to Lua and Isaac in general), but I found in my items.xml that they copied the book of belial line from ID #34 over to ID #59. I assume in this particular case that was to make it easier to have the birthright version work like the book of virtues instead of trying to make a single item do all of the work.
Outside of that I'm afraid I don't know exactly what you mean.
