### ISSUE TITLE
Bug with EntityNPC Morph

### ISSUE THREAD

**Issue by thicco-catto** [wofsauge/IsaacDocs#256]
When trying to change an entity using Morph you can transform it into any kind of champion no problem. However, if the entity is already a champion and you set the ChampionColorIdx to -1 the entity just keeps its champion color instead of turning into a regular enemy, like what the docs say.

**Comment by thicco-catto** [comment]
Sorry, I haven't really ever worked with github, why would I submit a pr?

**Comment by thicco-catto** [comment]
ok?

**Comment by Zamiell** [comment]
click on the edit button on the page you want to change
