### ISSUE TITLE
Incorrect entry order when sorting by integer enum value

### ISSUE THREAD

**Issue by ddeeddii** [wofsauge/IsaacDocs#306]
If an enum has a double digit value, and you sort the page by value, the order of displaying the enums is incorrect.

Example: 0->1->10->100->1000->101->etc.

You can reproduce this bug by going into any enum documentation page (like [EntityType](https://wofsauge.github.io/IsaacDocs/rep/enums/EntityType.html)) and clicking on the *value* field, you should get the following result: ![result](https://user-images.githubusercontent.com/80522865/171657699-a206bbe5-b1fa-46b0-b3a7-b4dbac5c6ca2.png)

Integer 'values' should be treated as integers and sorted as such, not sorted alphabetically like strings.
It's not a huge issue but it's kind of annoying when switching between sorting by enumerators and values.

**Comment by wofsauge** [comment]
Thanks for the bug report. This issue should now be fixed with commit f3337eaed46aed0d9fec8c9e553e5011941f5655.
