### ISSUE TITLE
An interactive faq to fix common installation and bug report issues

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/IsaacDocs#379]
Because of an increase in people failing to install and properly reporting issues, here a new feature idea.

A web page with a simple questionnaire style ui, where you find quick fixes for common mod problems. 

Example:

Issue: "Mod not working"
Questions:

Can you see the mod in the mods menu?
- yes (will redirect to question "is the mod highlighted with black text like shown on this screenshot?"  
- no ( will redirect to question "have you installed the mod manually or did you subscribe on it via steam?")
- can't see a mods menu ( will show solution " you don't have the modding dlcs ab+ or repentance installed. You can't use mods from the steam workshop without them)

The goal is to guide the user thru the debug process easily and understandable

**Comment by jsgnextortex** [comment]
Here is a simplified flowchart that should cover a lot of cases, it will direct to the next question unless the answer is the one with the --, then it will just stop there.

1. Can you see a Mods menu in your main menu screen?
--No: You Need AB+ at least

2. Does the mod in question appear on the mods menu?
--No: Make sure you properly subscribe to the mod and then relaunch the game. If you dont own the game on steam then head to the folder where the game is installed and check if your mod is properly copied into the "mods" folder, if its not there then copy it.

3- Is the name of the mod in question faint color and washed out in the mods list?
--Yes: Press tab on the mod's list until mods become dark, if the mod in question is still faint then scroll down and press space on it until its dark.

3. Most of your current mods also wont work?. If so, Have you tried verifying the game files?
--No: Verify the game files and try again.

4. Do you see any errors in the console or log?
Yes: Make sure to copy these errors (including the numbers after the :) or screenshot them, then share them with the mod author.

4. Do you have the debug console on or do you know where the log file is?
--No: <link to the debug console wiki page> and the lod file is in Documents/Tboi Repentance/log.txt.

5. In case you checked the log, was the game opened between you finding the issue and you checking the log?
--Yes: Dont do that, try to replicate the issue and then immediately check the log after it happens(if the game crashes dont open it again until you check the log).

5. Report your issue to the author and be as explicit as possible. If you have a way to replicate the issue, please explain it step by step.

**Comment by wofsauge** [comment]
Feature was added to the FAQ section now :)
