### ISSUE TITLE
document ProjectilesMode

### ISSUE THREAD

**Issue by piber20** [wofsauge/IsaacDocs#43]
https://moddingofisaac.com/docs/class_entity_n_p_c.html#a6fbab8146c9cd0c7c64cdf0599a85a7f

0 : single projectile
1 : two projectiles (uses params.Spread)
2 : three projectiles (uses params.Spread)
3 : three projectiles (uses params.Spread, more spread out?)
4 : four projectiles (uses params.Spread)
5 : five projectiles (uses params.Spread)
6 : four projectiles in a + pattern (uses velocity.x as speed)
7 : four projectiles in a x pattern (uses velocity.x as speed)
8 : eight projectiles in a star pattern (uses velocity.x as speed)
9 : N projectiles in a circle (velocity.x = speed, velocity.y = N, params.FireDirectionLimit and params.DotProductLimit to fire in an arc only)

**Comment by wofsauge** [comment]
Sorry for the delay. Added these informations now :)
