### ISSUE TITLE
Entity Overview page suggestions

### ISSUE THREAD

**Issue by Cuerzor** [wofsauge/IsaacDocs#472]
![QQ截图20241026132758](https://github.com/user-attachments/assets/c98590d7-772a-4d1b-87b5-42609927fc2e)

**Comment by Zamiell** [comment]
can you submit a pull request instead of posting a screenshot?

**Comment by Cuerzor** [comment]
okay let me try

**Comment by Zamiell** [comment]
good pr thanks

**Comment by wofsauge** [comment]
thanks for the PR :) its merged now
