### ISSUE TITLE
should I1, I2, V1, and V2's uses be documented?

### ISSUE THREAD

**Issue by piber20** [wofsauge/IsaacDocs#66]
i discovered The Frail sets I2 to 1 when he enters his second phase (the skeleton) and im wondering how this would be documented. i dont know if it would be out of scope, or too much info, or what. the notes for them could get massive if they document every base game npc

**Comment by Zamiell** [comment]
Well there's an entities section now, so this can go there.

**Comment by wofsauge** [comment]
Ive added a small explaination to each of the variables now. It also contains your example of the Frail in order to make he usage a bit more clear
