### ISSUE TITLE
defining an extra variable for the bugged callbacks actually doesn't let other callbacks work

### ISSUE THREAD

**Issue by piber20** [wofsauge/IsaacDocs#67]
discovered this the hard way. i think its caused if you add a callback with no extra var first, then try adding callbacks with extra vars, it wont let the later ones be added

some specific note should be added to these, perhaps also mentioning callback merger to fix it

**Comment by wofsauge** [comment]
Can you elaborate on that a bit more or give an example? i dont really understand this completely
