### ISSUE TITLE
Charge should not exist under EntityPlayer

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#88]
I think it doesn't exist?

**Comment by Zamiell** [comment]
Actually it should be renamed to GetEntityCharge()

**Comment by wofsauge** [comment]
What do you mean with that? What function should be renamed exactly?

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/118033087-663fdf80-b336-11eb-9939-7332692c624f.png)

**Comment by wofsauge** [comment]
fixed now
